spring:
  cloud:
    openfeign:
      client:
        config:
          default:
            logger-level: full
            connect-timeout: 3000
            read-timeout: 2000
    sentinel:
      transport:
        dashboard: localhost:8080
      eager: true
      web-context-unify: false
#          service-product:
#            logger-level: full
#            connect-timeout: 3000
#            read-timeout: 5000

feign:
  sentinel:
    enabled: true